server:
  port: 30010

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.115:8848
  application:
    name: Campus-Transaction-cart

  redis:
    host: 192.168.1.115
    port: 6379
  session:
    store-type: redis

campus:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
