spring:
  cloud:
    gateway:
      routes:
        #   product
        - id: product_route
          uri: lb://Campus-Transaction-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        #   third_party
        - id: third_patry_route
          uri: lb://Campus-Transaction-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>/?.*), $\{segment}
      #   member
        - id: member_route
          uri: lb://Campus-Transaction-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
      #   coupon
        - id: coupon_route
          uri: lb://Campus-Transaction-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
      #   ware
        - id: ware_route
          uri: lb://Campus-Transaction-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast$\{segment}
        - id: campus_search_route
          uri: lb://Campus-Transaction-search
          predicates:
            - Host=search.campus.com
      # nginx服务转发
        - id: campus_host_route
          uri: lb://Campus-Transaction-product
          predicates:
            - Host=campus.com
    nacos:
      discovery:
        server-addr: 192.168.1.115:8848
  application:
    name: Campus-Transaction-gateway

server:
  port: 88
