spring:
  application:
    name: Campus-Transaction-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.115:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.115
    port: 6379
  session:
    store-type: redis
server:
  port: 12000