spring:
  datasource:
    username: root
    password: LY0115..
    url: jdbc:mysql://192.168.1.115:3306/campus_transaction_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.115:8848
      config:
        server-addr: 192.168.1.115:8848
  application:
    name: Campus-Transaction-coupon

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


server:
  port: 7000

coupon:
  user:
    name: liyang
    age: 18